from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.Domains.Procurement.models.order import (
    Order,
    OrderAllocation,
    OrderAudit,
    OrderCreation,
    OrderDelivery,
    OrderLine,
)


class OrderStore(Protocol):
    async def lock(self, key: str) -> None: ...
    async def add(self, entity): ...
    async def creation(self, key: str) -> OrderCreation | None: ...
    async def allocations(self, ids: list[UUID]) -> list[OrderAllocation]: ...
    async def get(self, order_id: UUID, lock: bool = False) -> Order | None: ...
    async def list(self, limit, offset, status=None, supplier_id=None, warehouse_id=None): ...
    async def lines(self, order_id: UUID) -> list[OrderLine]: ...
    async def delete_line(self, line: OrderLine) -> None: ...
    async def release_allocations(self, order_id: UUID) -> None: ...
    async def audits(self, order_id: UUID, limit: int, offset: int) -> list[OrderAudit]: ...
    async def delivery(self, order_id: UUID) -> OrderDelivery | None: ...
    async def successor(self, order_id: UUID) -> Order | None: ...
    async def revision_event(self, order_id: UUID) -> OrderAudit | None: ...
