"""add saved 1c REST report profiles"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "5eeb25201444"
down_revision = "e27cb30a025e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_rest_reports",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("items_path", sa.String(length=200), nullable=False),
        sa.Column("column_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quantity_multiplier", sa.Integer(), nullable=False),
        sa.Column("auth_env", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity_multiplier IN (-1, 1)", name="ck_rest_report_sign"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_integration_rest_reports_source_id"),
        "integration_rest_reports",
        ["source_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_integration_rest_reports_source_id"), table_name="integration_rest_reports"
    )
    op.drop_table("integration_rest_reports")
    # ### end Alembic commands ###
