"""add user profile and security sessions"""

import sqlalchemy as sa
from alembic import op

revision = "80569e449f7a"
down_revision = "ad080ada50ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_security_sessions_expires_at"), "security_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_security_sessions_user_id"), "security_sessions", ["user_id"], unique=False
    )
    # Preserve existing names verbatim; guessing how to split them would lose information.
    op.alter_column("users", "name", new_column_name="first_name")
    op.add_column("users", sa.Column("last_name", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("middle_name", sa.String(length=200), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(length=32), nullable=True))
    op.add_column("users", sa.Column("email", sa.String(length=254), nullable=True))
    op.add_column("users", sa.Column("password_hash", sa.String(length=512), nullable=True))
    op.create_index(
        "ix_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "first_name", new_column_name="name")
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "email")
    op.drop_column("users", "phone")
    op.drop_column("users", "middle_name")
    op.drop_column("users", "last_name")
    op.drop_index(op.f("ix_security_sessions_user_id"), table_name="security_sessions")
    op.drop_index(op.f("ix_security_sessions_expires_at"), table_name="security_sessions")
    op.drop_table("security_sessions")
    # ### end Alembic commands ###
