"""add replenishment procurement and 1c exchange"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "9860745f4be3"
down_revision = "b735e3320afe"
branch_labels = None
depends_on = None


def upgrade():
    # PostgreSQL 18 generates time-ordered IDs; existing identifiers are unchanged.
    for table in ("users", "roles", "permissions", "files", "jobs", "notes", "security_sessions"):
        op.alter_column(table, "id", server_default=sa.text("uuidv7()"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_sources",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("system", sa.String(length=30), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.String(length=200), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "procurement_order_creations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("order_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "catalog_categories",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("review_days", sa.Integer(), nullable=False),
        sa.Column("safety_days", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_catalog_categories_source_id"), "catalog_categories", ["source_id"], unique=False
    )
    op.create_table(
        "catalog_suppliers",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_catalog_suppliers_source_id"), "catalog_suppliers", ["source_id"], unique=False
    )
    op.create_table(
        "catalog_warehouses",
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("organization_external_id", sa.String(length=200), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_catalog_warehouses_source_id"), "catalog_warehouses", ["source_id"], unique=False
    )
    op.create_table(
        "data_import_batches",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("base_revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_import_batches_source_id"), "data_import_batches", ["source_id"], unique=False
    )
    op.create_table(
        "exchange_batches",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("batch_key", sa.String(length=200), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.String(length=200), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "batch_key"),
    )
    op.create_index(
        op.f("ix_exchange_batches_source_id"), "exchange_batches", ["source_id"], unique=False
    )
    op.create_table(
        "procurement_orders",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_name", sa.String(length=500), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("external_references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(status = 'draft' AND approved_snapshot IS NULL AND approved_at IS NULL "
            "AND approved_by IS NULL) OR (status = 'approved' AND approved_snapshot IS NOT NULL "
            "AND approved_at IS NOT NULL AND approved_by IS NOT NULL)",
            name="ck_order_approval",
        ),
        sa.CheckConstraint("status IN ('draft', 'approved')", name="ck_order_status"),
        sa.CheckConstraint("version >= 1 AND revision >= 1", name="ck_order_version"),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_procurement_orders_status"), "procurement_orders", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_procurement_orders_supplier_id"),
        "procurement_orders",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_orders_warehouse_id"),
        "procurement_orders",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "catalog_products",
        sa.Column("sku", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=200), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("characteristic_external_id", sa.String(length=200), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("pack_size", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("min_order_qty", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["catalog_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["catalog_suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(op.f("ix_catalog_products_sku"), "catalog_products", ["sku"], unique=False)
    op.create_index(
        op.f("ix_catalog_products_source_id"), "catalog_products", ["source_id"], unique=False
    )
    op.create_table(
        "procurement_order_allocations",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["procurement_orders.id"],
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    op.create_index(
        op.f("ix_procurement_order_allocations_order_id"),
        "procurement_order_allocations",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "procurement_order_audits",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["procurement_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_procurement_order_audits_order_id"),
        "procurement_order_audits",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "procurement_order_deliveries",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("external_document_id", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status != 'accepted' OR external_document_id IS NOT NULL",
            name="ck_order_delivery_reference",
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')", name="ck_order_delivery_status"
        ),
        sa.CheckConstraint("revision >= 1", name="ck_order_delivery_revision"),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["procurement_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "procurement_order_lines",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=1000), nullable=False),
        sa.Column("unit", sa.String(length=100), nullable=False),
        sa.Column("recommended_quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "quantity > 0 AND recommended_quantity > 0", name="ck_order_line_quantity"
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["procurement_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_procurement_order_lines_order_id"),
        "procurement_order_lines",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_procurement_order_lines_recommendation_id"),
        "procurement_order_lines",
        ["recommendation_id"],
        unique=False,
    )
    op.create_table(
        "replenishment_runs",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("algorithm_version", sa.String(length=64), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("created_by", "idempotency_key"),
    )
    op.create_index(
        op.f("ix_replenishment_runs_status"), "replenishment_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_replenishment_runs_warehouse_id"),
        "replenishment_runs",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_growth",
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("mode", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["catalog_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_inventory_growth_category_id"), "inventory_growth", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_growth_product_id"), "inventory_growth", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_growth_source_id"), "inventory_growth", ["source_id"], unique=False
    )
    op.create_table(
        "inventory_inbound",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("document_id", sa.String(length=200), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["catalog_suppliers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_inventory_inbound_product_id"), "inventory_inbound", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_inbound_source_id"), "inventory_inbound", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_inbound_warehouse_id"),
        "inventory_inbound",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_sales",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("document_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("document_id", sa.String(length=200), nullable=False),
        sa.Column("line_id", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("client_id", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(op.f("ix_inventory_sales_date"), "inventory_sales", ["date"], unique=False)
    op.create_index(
        op.f("ix_inventory_sales_product_id"), "inventory_sales", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_sales_source_id"), "inventory_sales", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_sales_warehouse_id"), "inventory_sales", ["warehouse_id"], unique=False
    )
    op.create_table(
        "inventory_snapshots",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("reserved", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_inventory_snapshots_as_of"), "inventory_snapshots", ["as_of"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_snapshots_product_id"),
        "inventory_snapshots",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_snapshots_source_id"), "inventory_snapshots", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_snapshots_warehouse_id"),
        "inventory_snapshots",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_stockouts",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("start", sa.Date(), nullable=False),
        sa.Column("end", sa.Date(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["catalog_warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "external_id"),
    )
    op.create_index(
        op.f("ix_inventory_stockouts_product_id"),
        "inventory_stockouts",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_stockouts_source_id"), "inventory_stockouts", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_stockouts_warehouse_id"),
        "inventory_stockouts",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "replenishment_recommendations",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("unit", sa.String(length=100), nullable=False),
        sa.Column("recommended_quantity", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("urgency", sa.String(length=20), nullable=False),
        sa.Column("explanation", sa.String(length=2000), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["replenishment_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "product_id"),
    )
    op.create_index(
        op.f("ix_replenishment_recommendations_product_id"),
        "replenishment_recommendations",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_replenishment_recommendations_run_id"),
        "replenishment_recommendations",
        ["run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_replenishment_recommendations_supplier_id"),
        "replenishment_recommendations",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_replenishment_recommendations_urgency"),
        "replenishment_recommendations",
        ["urgency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_replenishment_recommendations_warehouse_id"),
        "replenishment_recommendations",
        ["warehouse_id"],
        unique=False,
    )
    op.add_column(
        "jobs",
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
    )
    op.add_column(
        "jobs", sa.Column("dispatch_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("jobs", sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    for table in ("users", "roles", "permissions", "files", "jobs", "notes", "security_sessions"):
        op.alter_column(table, "id", server_default=None)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "dispatched_at")
    op.drop_column("jobs", "dispatch_count")
    op.drop_column("jobs", "payload")
    op.drop_index(
        op.f("ix_replenishment_recommendations_warehouse_id"),
        table_name="replenishment_recommendations",
    )
    op.drop_index(
        op.f("ix_replenishment_recommendations_urgency"), table_name="replenishment_recommendations"
    )
    op.drop_index(
        op.f("ix_replenishment_recommendations_supplier_id"),
        table_name="replenishment_recommendations",
    )
    op.drop_index(
        op.f("ix_replenishment_recommendations_run_id"), table_name="replenishment_recommendations"
    )
    op.drop_index(
        op.f("ix_replenishment_recommendations_product_id"),
        table_name="replenishment_recommendations",
    )
    op.drop_table("replenishment_recommendations")
    op.drop_index(op.f("ix_inventory_stockouts_warehouse_id"), table_name="inventory_stockouts")
    op.drop_index(op.f("ix_inventory_stockouts_source_id"), table_name="inventory_stockouts")
    op.drop_index(op.f("ix_inventory_stockouts_product_id"), table_name="inventory_stockouts")
    op.drop_table("inventory_stockouts")
    op.drop_index(op.f("ix_inventory_snapshots_warehouse_id"), table_name="inventory_snapshots")
    op.drop_index(op.f("ix_inventory_snapshots_source_id"), table_name="inventory_snapshots")
    op.drop_index(op.f("ix_inventory_snapshots_product_id"), table_name="inventory_snapshots")
    op.drop_index(op.f("ix_inventory_snapshots_as_of"), table_name="inventory_snapshots")
    op.drop_table("inventory_snapshots")
    op.drop_index(op.f("ix_inventory_sales_warehouse_id"), table_name="inventory_sales")
    op.drop_index(op.f("ix_inventory_sales_source_id"), table_name="inventory_sales")
    op.drop_index(op.f("ix_inventory_sales_product_id"), table_name="inventory_sales")
    op.drop_index(op.f("ix_inventory_sales_date"), table_name="inventory_sales")
    op.drop_table("inventory_sales")
    op.drop_index(op.f("ix_inventory_inbound_warehouse_id"), table_name="inventory_inbound")
    op.drop_index(op.f("ix_inventory_inbound_source_id"), table_name="inventory_inbound")
    op.drop_index(op.f("ix_inventory_inbound_product_id"), table_name="inventory_inbound")
    op.drop_table("inventory_inbound")
    op.drop_index(op.f("ix_inventory_growth_source_id"), table_name="inventory_growth")
    op.drop_index(op.f("ix_inventory_growth_product_id"), table_name="inventory_growth")
    op.drop_index(op.f("ix_inventory_growth_category_id"), table_name="inventory_growth")
    op.drop_table("inventory_growth")
    op.drop_index(op.f("ix_replenishment_runs_warehouse_id"), table_name="replenishment_runs")
    op.drop_index(op.f("ix_replenishment_runs_status"), table_name="replenishment_runs")
    op.drop_table("replenishment_runs")
    op.drop_index(
        op.f("ix_procurement_order_lines_recommendation_id"), table_name="procurement_order_lines"
    )
    op.drop_index(op.f("ix_procurement_order_lines_order_id"), table_name="procurement_order_lines")
    op.drop_table("procurement_order_lines")
    op.drop_table("procurement_order_deliveries")
    op.drop_index(
        op.f("ix_procurement_order_audits_order_id"), table_name="procurement_order_audits"
    )
    op.drop_table("procurement_order_audits")
    op.drop_index(
        op.f("ix_procurement_order_allocations_order_id"),
        table_name="procurement_order_allocations",
    )
    op.drop_table("procurement_order_allocations")
    op.drop_index(op.f("ix_catalog_products_source_id"), table_name="catalog_products")
    op.drop_index(op.f("ix_catalog_products_sku"), table_name="catalog_products")
    op.drop_table("catalog_products")
    op.drop_index(op.f("ix_procurement_orders_warehouse_id"), table_name="procurement_orders")
    op.drop_index(op.f("ix_procurement_orders_supplier_id"), table_name="procurement_orders")
    op.drop_index(op.f("ix_procurement_orders_status"), table_name="procurement_orders")
    op.drop_table("procurement_orders")
    op.drop_index(op.f("ix_exchange_batches_source_id"), table_name="exchange_batches")
    op.drop_table("exchange_batches")
    op.drop_index(op.f("ix_data_import_batches_source_id"), table_name="data_import_batches")
    op.drop_table("data_import_batches")
    op.drop_index(op.f("ix_catalog_warehouses_source_id"), table_name="catalog_warehouses")
    op.drop_table("catalog_warehouses")
    op.drop_index(op.f("ix_catalog_suppliers_source_id"), table_name="catalog_suppliers")
    op.drop_table("catalog_suppliers")
    op.drop_index(op.f("ix_catalog_categories_source_id"), table_name="catalog_categories")
    op.drop_table("catalog_categories")
    op.drop_table("procurement_order_creations")
    op.drop_table("integration_sources")
    # ### end Alembic commands ###
