"""allow source cancellations and rejected order revisions"""

import sqlalchemy as sa
from alembic import op

revision = "aa936937a028"
down_revision = "9860745f4be3"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("procurement_orders", sa.Column("supersedes_order_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_order_supersedes",
        "procurement_orders",
        "procurement_orders",
        ["supersedes_order_id"],
        ["id"],
    )
    op.create_unique_constraint(
        "uq_order_supersedes", "procurement_orders", ["supersedes_order_id"]
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_growth",
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "inventory_stockouts",
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_constraint("uq_order_supersedes", "procurement_orders", type_="unique")
    op.drop_constraint("fk_order_supersedes", "procurement_orders", type_="foreignkey")
    op.drop_column("procurement_orders", "supersedes_order_id")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inventory_stockouts", "active")
    op.drop_column("inventory_growth", "active")
    # ### end Alembic commands ###
