"""add durable partner workbook import packages"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "e27cb30a025e"
down_revision = "aa936937a028"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_packages",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("files", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("issues", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("products", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("processed_rows", sa.Integer(), nullable=False),
        sa.Column("expected_revision", sa.Integer(), nullable=True),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_index(
        op.f("ix_import_packages_source_id"), "import_packages", ["source_id"], unique=False
    )
    op.create_table(
        "import_identities",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("code", sa.String(length=200), nullable=False),
        sa.Column("characteristic", sa.String(length=200), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["catalog_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["integration_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "kind", "code", "characteristic"),
    )
    op.create_index(
        op.f("ix_import_identities_source_id"), "import_identities", ["source_id"], unique=False
    )
    op.create_table(
        "import_package_chunks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["import_packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package_id", "position"),
    )
    op.create_index(
        op.f("ix_import_package_chunks_package_id"),
        "import_package_chunks",
        ["package_id"],
        unique=False,
    )
    op.create_table(
        "import_package_evidence",
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("package_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_id"],
            ["import_packages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("package_id", "position"),
    )
    op.create_index(
        op.f("ix_import_package_evidence_package_id"),
        "import_package_evidence",
        ["package_id"],
        unique=False,
    )
    op.add_column(
        "catalog_products",
        sa.Column(
            "data_quality",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("catalog_products", "data_quality")
    op.drop_index(
        op.f("ix_import_package_evidence_package_id"), table_name="import_package_evidence"
    )
    op.drop_table("import_package_evidence")
    op.drop_index(op.f("ix_import_package_chunks_package_id"), table_name="import_package_chunks")
    op.drop_table("import_package_chunks")
    op.drop_index(op.f("ix_import_identities_source_id"), table_name="import_identities")
    op.drop_table("import_identities")
    op.drop_index(op.f("ix_import_packages_source_id"), table_name="import_packages")
    op.drop_table("import_packages")
    # ### end Alembic commands ###
